name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.5.1'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        if (Test-Path ".npmrc") { Remove-Item ".npmrc" -Force }
        npm cache verify
        npm install
      shell: powershell
      
    - name: Build application
      run: npm run dist
      
    - name: Create zip archive
      run: |
        cd dist
        Compress-Archive -Path win-unpacked -DestinationPath easysmart-electron-win.zip
      shell: powershell
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/easysmart-electron-win.zip
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}